from fastapi import FastAPI, Depends, HTTPException, Security
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
from pydantic import BaseModel
from typing import List
import os
from langchain_classic.chains.retrieval import create_retrieval_chain
from langchain_classic.chains.history_aware_retriever import create_history_aware_retriever
from langchain_classic.chains.combine_documents import create_stuff_documents_chain
from langchain_ollama.chat_models import ChatOllama
from langchain_ollama.embeddings import OllamaEmbeddings
from langchain_community.document_loaders import CSVLoader
from langchain_community.vectorstores import FAISS
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from fpdf import FPDF
from datetime import datetime

# 1. THE PDF DESIGNER FUNCTION
def generate_proposal_pdf(client_query, ai_pitch):
    pdf = FPDF()
    pdf.add_page()
    
    # Header: Branding
    pdf.set_font("Arial", 'B', 24)
    pdf.set_text_color(0, 212, 255) # Empire Blue
    pdf.cell(0, 20, "THE EMPIRE AI AGENCY", ln=True, align='C')
    
    # Subheader
    pdf.set_font("Arial", 'B', 12)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 10, f"AI Assistant Response | Generated on: {datetime.now().strftime('%d-%m-%Y')}", ln=True, align='C')
    pdf.ln(10)

    # Section: Executive Summary
    pdf.set_font("Arial", 'B', 14)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, "1. Your Query", ln=True)
    pdf.set_font("Arial", '', 11)
    pdf.multi_cell(0, 7, f"Your question: '{client_query}'")
    pdf.ln(5)

    # Section: AI Response
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(0, 10, "2. AI Assistant Response", ln=True)
    pdf.set_font("Arial", '', 11)
    pdf.multi_cell(0, 7, ai_pitch)
    pdf.ln(5)

    # Section: Information
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(0, 10, "3. About This Response", ln=True)
    pdf.set_font("Arial", '', 11)
    pdf.multi_cell(0, 7, "This response was generated by an AI Assistant. For more detailed information or follow-up questions, please ask again.")

    # Footer
    pdf.ln(20)
    pdf.set_font("Arial", 'I', 10)
    pdf.cell(0, 10, "Generated by THE EMPIRE AI Assistant", ln=True, align='C')

    # Save to your Outbox folder so Node.js can see it!
    filename = f"Proposal_Project_{datetime.now().strftime('%H%M%S')}.pdf"
    # Use absolute path to backend's outbox directory
    script_dir = os.path.dirname(os.path.abspath(__file__))
    outbox_dir = os.path.join(os.path.dirname(script_dir), "backend", "outbox")
    
    # Create outbox directory if it doesn't exist
    os.makedirs(outbox_dir, exist_ok=True)
    
    filepath = os.path.join(outbox_dir, filename)
    pdf.output(filepath)
    return filename

app = FastAPI()

security = HTTPBearer()
AI_SERVICE_TOKEN = os.getenv("AI_SERVICE_TOKEN", "default-ai-service-token-change-me")

def verify_token(credentials: HTTPAuthorizationCredentials = Security(security)):
    if credentials.credentials != AI_SERVICE_TOKEN:
        raise HTTPException(
            status_code=401,
            detail="Invalid or missing service token"
        )
    return credentials.credentials

llm = ChatOllama(model="llama3.2")

script_dir = os.path.dirname(os.path.abspath(__file__))
csv_path = os.path.join(script_dir, "my_agency_services.csv")

if not os.path.exists(csv_path):
    raise FileNotFoundError(f"CSV data file not found: {csv_path}")

loader = CSVLoader(file_path=csv_path)

# Initialize vector_db and chains safely with fallback
vector_db = None
retriever = None
history_aware_retriever = None

try:
    documents = loader.load()
    vector_db = FAISS.from_documents(documents, OllamaEmbeddings(model="llama3.2"))
    retriever = vector_db.as_retriever()

    contextualize_q_system_prompt = """Given a chat history and the latest user question which might reference context in the chat history, formulate a standalone question which can be understood without the chat history. Do NOT answer the question, just reformulate it if needed and otherwise return it as is."""

    contextualize_q_prompt = ChatPromptTemplate.from_messages([
        ("system", contextualize_q_system_prompt),
        MessagesPlaceholder("chat_history"),
        ("human", "{input}"),
    ])

    history_aware_retriever = create_history_aware_retriever(llm, retriever, contextualize_q_prompt)
    print("AI Service initialized FAISS vector DB and RAG chains successfully with Ollama.")
except Exception as e:
    print(f"Warning: Could not connect to Ollama for embedding initialization ({e}). RAG will run in fallback mode.")

# PERSONAS - Multiple AI Expert Modes
PERSONAS = {
    "sales": "You are a Sales AI for THE EMPIRE. Use the following pieces of retrieved context to answer the user's question. Context: {context}",
    "hr_screener": "You are an expert HR Manager. Compare the resume provided in context to the user's requirements. Rank candidates by skill-match percentage. Context: {context}",
    "legal_pro": "You are a Senior Legal Consultant. Summarize legal documents and identify potential risks or missing clauses. Context: {context}",
    "review_analyst": "You are a Data Scientist. Analyze customer reviews to identify 'Pros', 'Cons', and 'Feature Requests'. Be data-driven. Context: {context}",
    "real_estate": "You are a Real Estate Sales Pro. Suggest properties from the catalog and answer questions about amenities, carpet area, and RERA status. Context: {context}"
}

class ChatMessage(BaseModel):
    role: str
    content: str

class ChatRequest(BaseModel):
    messages: List[ChatMessage]
    persona: str = "sales"  # Default to sales persona

@app.post("/ask_ai")
async def ask_ai(request: ChatRequest, token: str = Depends(verify_token)):
    history = []
    for msg in request.messages[:-1]:
        role = msg.role.lower()
        if role == "user":
            history.append(("human", msg.content))
        else:
            history.append(("ai", msg.content))

    current_input = request.messages[-1].content
    persona_prompt = PERSONAS.get(request.persona, PERSONAS["sales"])
    
    answer = None
    if history_aware_retriever is not None:
        try:
            dynamic_qa_prompt = ChatPromptTemplate.from_messages([
                ("system", persona_prompt),
                MessagesPlaceholder("chat_history"),
                ("human", "{input}"),
            ])
            dynamic_question_answer_chain = create_stuff_documents_chain(llm, dynamic_qa_prompt)
            dynamic_rag_chain = create_retrieval_chain(history_aware_retriever, dynamic_question_answer_chain)
            
            response = dynamic_rag_chain.invoke({"chat_history": history, "input": current_input})
            answer = response.get("answer") if isinstance(response, dict) else str(response)
        except Exception as err:
            print(f"RAG invocation error: {err}")
            answer = None

    if answer is None:
        # Fallback response when Ollama is offline or unavailable
        answer = f"Thank you for contacting THE EMPIRE AI Assistant regarding: '{current_input}'. Our system is currently operating in fallback mode. We have recorded your query for persona '{request.persona}' and will assist you shortly."

    # Generate PDF proposal
    pdf_filename = generate_proposal_pdf(current_input, answer)

    return {"pitch": answer, "pdf_filename": pdf_filename}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="127.0.0.1", port=8001)