import type { Bot, BotCategory, AIProvider } from "@/types";

export const APP_NAME = "Nexora";
export const APP_TAGLINE = "Intelligence, Automated.";

export const NAV_ITEMS = [
  { label: "Dashboard", href: "/dashboard", icon: "LayoutDashboard" },
  { label: "Booking Hub", href: "/booking-hub", icon: "Brain" },
  { label: "Travel Booking", href: "/travel-booking", icon: "Plane" },
  { label: "Stock Intelligence", href: "/stock-intelligence", icon: "TrendingUp" },
  { label: "Career Accelerator", href: "/career-accelerator", icon: "GraduationCap" },

  { label: "Document Agent", href: "/document-agent", icon: "FileText" },
  { label: "Startup Co-Founder", href: "/startup-cofounder", icon: "Rocket" },
  { label: "Research Scientist", href: "/research-scientist", icon: "FlaskConical" },
  { label: "Business Automator", href: "/business-automator", icon: "Workflow" },
  { label: "Sales Agent", href: "/sales-agent", icon: "Target" },
  { label: "Bot Store", href: "/bots", icon: "Store" },
  { label: "WhatsApp", href: "/whatsapp", icon: "MessageCircle" },
  { label: "File Tracker", href: "/file-tracker", icon: "FileSearch" },
  { label: "AI Playground", href: "/ai-playground", icon: "Sparkles" },
  { label: "Settings", href: "/settings", icon: "Settings" },
] as const;

export const BOT_CATEGORIES: { label: string; value: BotCategory; icon: string }[] = [
  { label: "Automation", value: "automation", icon: "Zap" },
  { label: "Communication", value: "communication", icon: "MessageSquare" },
  { label: "Analytics", value: "analytics", icon: "BarChart3" },
  { label: "Productivity", value: "productivity", icon: "Target" },
  { label: "Customer Support", value: "customer-support", icon: "Headphones" },
  { label: "Marketing", value: "marketing", icon: "Megaphone" },
  { label: "Development", value: "development", icon: "Code2" },
  { label: "Finance", value: "finance", icon: "DollarSign" },
];

export const FEATURED_BOTS: Bot[] = [
  {
    id: "bot-hotel",
    name: "Hotel Booking Agent",
    description: "Search hotels, compare room features, manage bookings, and find the best deals with AI recommendations.",
    longDescription: "A smart, automated hotel broker that searches global inventories, compares prices, filters by ratings and amenities, and books double, suite, or deluxe rooms instantly.",
    icon: "Hotel",
    category: "automation",
    rating: 4.8,
    usageCount: 14500,
    price: "free",
    status: "active",
    features: ["Hotel Search", "Room Configuration", "Deals Comparison", "Instant Reservation", "Amenities Filter"],
    author: "Nexora",
    version: "1.0.0",
    createdAt: "2024-06-01",
    updatedAt: "2024-06-25",
  },
  {
    id: "bot-travel",
    name: "Travel Booking Agent",
    description: "Search flights, buses, and trains. Compare prices across carriers and book instantly with AI-powered trip planning.",
    longDescription: "A powerful multi-modal travel booking assistant that searches across airlines, bus operators, and rail networks to find the best routes, prices, and schedules — all in one interface.",
    icon: "Plane",
    category: "automation",
    rating: 4.9,
    usageCount: 28500,
    price: "free",
    status: "active",
    features: ["Flight Search", "Bus Routes", "Train Booking", "Price Comparison", "Trip Planning", "Instant Booking"],
    author: "Nexora",
    version: "1.0.0",
    createdAt: "2024-06-01",
    updatedAt: "2024-06-25",
  },
  {
    id: "bot-1",
    name: "WhatsApp AI Assistant",
    description: "Intelligent WhatsApp chatbot with natural language understanding and automated responses.",
    longDescription: "A powerful AI-driven WhatsApp assistant that handles customer inquiries, schedules appointments, and provides instant support 24/7.",
    icon: "MessageCircle",
    category: "communication",
    rating: 4.9,
    usageCount: 15420,
    price: "free",
    status: "active",
    features: ["Natural Language Processing", "Auto-replies", "Template Messages", "Multi-language"],
    author: "Nexora",
    version: "2.1.0",
    standaloneUrl: "http://localhost:3001",
    createdAt: "2024-01-15",
    updatedAt: "2024-03-10",
  },
  {
    id: "bot-2",
    name: "Stock Intelligence Agent",
    description: "Real-time stock analysis with RSI, MACD, Bollinger Bands, AI-powered buy/sell signals and portfolio tracking.",
    longDescription: "Transform raw market data into actionable insights with automated technical analysis, sentiment scoring, and AI-generated recommendations.",
    icon: "TrendingUp",
    category: "analytics",
    rating: 4.8,
    usageCount: 12300,
    price: "free",
    status: "active",
    features: ["Technical Analysis", "AI Signals", "Portfolio Tracker", "Watchlists", "Sentiment Analysis"],
    author: "Nexora",
    version: "2.0.0",
    createdAt: "2024-02-01",
    updatedAt: "2024-03-08",
  },
  {
    id: "bot-3",
    name: "Career Accelerator Agent",
    description: "ATS resume scoring, cover letter generation, interview prep, and skill gap analysis powered by AI.",
    longDescription: "Optimize your job search with AI-powered resume analysis, personalized cover letters, interview questions, and learning recommendations.",
    icon: "GraduationCap",
    category: "productivity",
    rating: 4.8,
    usageCount: 18200,
    price: "free",
    status: "active",
    features: ["ATS Scoring", "Cover Letters", "Interview Prep", "Skill Gap Analysis", "Resume Optimization"],
    author: "Nexora",
    version: "1.5.0",
    createdAt: "2024-01-20",
    updatedAt: "2024-03-12",
  },
  {
    id: "bot-productivity",
    name: "Productivity Agent",
    description: "AI-powered task management, daily planning, schedule generation, goal tracking, and smart reminders.",
    longDescription: "Stay organized and productive with an AI assistant that creates daily schedules, manages tasks, tracks goals, and ensures you never miss a deadline.",
    icon: "CheckSquare",
    category: "productivity",
    rating: 4.7,
    usageCount: 9800,
    price: "free",
    status: "active",
    features: ["Task Management", "AI Scheduling", "Goal Tracking", "Smart Reminders", "Daily Planning"],
    author: "Nexora",
    version: "1.0.0",
    createdAt: "2024-06-01",
    updatedAt: "2024-06-25",
  },
  {
    id: "bot-document",
    name: "Document Agent",
    description: "AI text summarization, document analysis, PDF generation, and key points extraction from any content.",
    longDescription: "Process documents intelligently — summarize long texts, extract key insights, generate professional PDFs, and analyze content structure with AI.",
    icon: "FileText",
    category: "productivity",
    rating: 4.6,
    usageCount: 7400,
    price: "free",
    status: "active",
    features: ["Text Summarization", "Document Analysis", "PDF Generation", "Key Point Extraction"],
    author: "Nexora",
    version: "1.0.0",
    createdAt: "2024-06-01",
    updatedAt: "2024-06-25",
  },
  {
    id: "bot-4",
    name: "Smart File Monitor",
    description: "AI-powered file tracking with change detection, audit logging, and alerts.",
    longDescription: "Monitor files and directories with intelligent change detection, version tracking, and comprehensive audit logs.",
    icon: "FileSearch",
    category: "productivity",
    rating: 4.6,
    usageCount: 6750,
    price: "free",
    status: "active",
    features: ["Change Detection", "Audit Logging", "Real-time Alerts", "Version History"],
    author: "Nexora",
    version: "1.5.0",
    createdAt: "2024-02-10",
    updatedAt: "2024-03-11",
  },
  {
    id: "bot-5",
    name: "Startup Co-Founder Agent",
    description: "AI-powered startup idea validation with SWOT analysis, market scoring, and revenue modeling.",
    icon: "Rocket",
    category: "analytics",
    rating: 4.7,
    usageCount: 8900,
    price: "free",
    status: "active",
    features: ["Idea Validation", "SWOT Analysis", "Market Scoring", "Revenue Model", "Competitor Research"],
    author: "Nexora",
    version: "1.3.0",
    createdAt: "2024-01-05",
    updatedAt: "2024-03-09",
  },
  {
    id: "bot-compass",
    name: "Compass Travel Advisor",
    description: "Bespoke travel planner with specialized agent roles, real-time map integration, and automated itinerary tracking.",
    longDescription: "Compass is an advanced, multi-role travel consultant. It automatically tracks your travel details (duration, budget, traveler count, interests) to compile a custom passport and syncs with live Google Maps, all while allowing you to choose specialized planning styles.",
    icon: "Compass",
    category: "automation",
    rating: 4.9,
    usageCount: 14200,
    price: "free",
    status: "active",
    features: ["Specialized Advisor Roles", "Real-Time Map Sync", "Itinerary Generation", "Automated Passport Tracking", "Ollama & Gemini Support"],
    author: "Nexora",
    version: "1.0.0",
    createdAt: "2026-07-13",
    updatedAt: "2026-07-13",
  },
  {
    id: "bot-sales",
    name: "AI Sales Agent",
    description: "AI-powered lead discovery, personalized email outreach, and meeting scheduling for startups & SaaS.",
    longDescription: "Transform your sales pipeline with an intelligent agent that finds qualified leads, enriches prospect data, generates personalized cold emails, and schedules meetings — all powered by AI.",
    icon: "Target",
    category: "automation",
    rating: 4.9,
    usageCount: 11200,
    price: "free",
    status: "active",
    features: ["Lead Discovery", "AI Lead Scoring", "Email Generation", "Meeting Scheduling", "Lead Enrichment", "Pipeline Analytics"],
    author: "Nexora",
    version: "1.0.0",
    createdAt: "2026-07-29",
    updatedAt: "2026-07-29",
  },
];

export const AI_PROVIDERS: AIProvider[] = [
  {
    id: "kimi",
    name: "Kimi (Moonshot AI)",
    icon: "Moon",
    status: "active",
    models: [
      { id: "moonshot-v1-128k", name: "Moonshot v1 128K", providerId: "kimi", maxTokens: 128000, costPer1kTokens: 0.012, capabilities: ["text", "code", "reasoning", "long-context"] },
      { id: "moonshot-v1-32k", name: "Moonshot v1 32K", providerId: "kimi", maxTokens: 32000, costPer1kTokens: 0.008, capabilities: ["text", "code", "reasoning"] },
      { id: "moonshot-v1-8k", name: "Moonshot v1 8K", providerId: "kimi", maxTokens: 8192, costPer1kTokens: 0.004, capabilities: ["text", "code"] },
    ],
  },
  {
    id: "gemini",
    name: "Google Gemini",
    icon: "Sparkles",
    status: "active",
    models: [
      { id: "gemini-pro", name: "Gemini Pro", providerId: "gemini", maxTokens: 32000, costPer1kTokens: 0.001, capabilities: ["text", "code", "reasoning"] },
      { id: "gemini-pro-vision", name: "Gemini Pro Vision", providerId: "gemini", maxTokens: 16000, costPer1kTokens: 0.002, capabilities: ["text", "vision", "code"] },
    ],
  },
  {
    id: "openai",
    name: "OpenAI",
    icon: "Brain",
    status: "active",
    models: [
      { id: "gpt-4", name: "GPT-4", providerId: "openai", maxTokens: 8192, costPer1kTokens: 0.03, capabilities: ["text", "code", "reasoning"] },
      { id: "gpt-4-turbo", name: "GPT-4 Turbo", providerId: "openai", maxTokens: 128000, costPer1kTokens: 0.01, capabilities: ["text", "code", "reasoning", "vision"] },
      { id: "gpt-3.5-turbo", name: "GPT-3.5 Turbo", providerId: "openai", maxTokens: 16385, costPer1kTokens: 0.001, capabilities: ["text", "code"] },
    ],
  },
  {
    id: "claude",
    name: "Anthropic Claude",
    icon: "Bot",
    status: "active",
    models: [
      { id: "claude-3-opus", name: "Claude 3 Opus", providerId: "claude", maxTokens: 200000, costPer1kTokens: 0.015, capabilities: ["text", "code", "reasoning", "vision"] },
      { id: "claude-3-sonnet", name: "Claude 3 Sonnet", providerId: "claude", maxTokens: 200000, costPer1kTokens: 0.003, capabilities: ["text", "code", "reasoning", "vision"] },
    ],
  },
  {
    id: "groq",
    name: "Groq",
    icon: "Zap",
    status: "active",
    models: [
      { id: "llama-3-70b", name: "LLaMA 3 70B", providerId: "groq", maxTokens: 8192, costPer1kTokens: 0.0007, capabilities: ["text", "code"] },
      { id: "mixtral-8x7b", name: "Mixtral 8x7B", providerId: "groq", maxTokens: 32768, costPer1kTokens: 0.0003, capabilities: ["text", "code"] },
    ],
  },
  {
    id: "ollama",
    name: "Ollama (Local)",
    icon: "Server",
    status: "active",
    models: [
      { id: "llama3", name: "LLaMA 3", providerId: "ollama", maxTokens: 8192, costPer1kTokens: 0, capabilities: ["text", "code"] },
      { id: "mistral", name: "Mistral", providerId: "ollama", maxTokens: 8192, costPer1kTokens: 0, capabilities: ["text", "code"] },
    ],
  },
];

export const STATS = [
  { label: "Autonomous Agents", value: 9, suffix: "" },
  { label: "AI Models Connected", value: 9, suffix: "+" },
  { label: "System Latency", value: 1.2, suffix: "s avg" },
  { label: "Platform Openness", value: 100, suffix: "%" },
];

export const HOW_IT_WORKS = [
  {
    step: 1,
    title: "Choose Your Agent",
    description: "Browse our suite of AI agents built for travel, finance, career, productivity, and more. Each one is production-ready.",
  },
  {
    step: 2,
    title: "Configure & Deploy",
    description: "Customize your agent with our intuitive setup. Connect APIs, set preferences, and define workflows in seconds.",
  },
  {
    step: 3,
    title: "Automate & Scale",
    description: "Watch your agents work autonomously. Track performance in real-time and scale effortlessly as your needs grow.",
  },
];
